// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rustylibFFI)
import rustylibFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rustylib_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rustylib_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol FfiMempoolProtocol : AnyObject {
    
    func flush() throws 
    
    func generation()  -> UInt64
    
    func liveCount()  -> UInt32
    
    func meta()  -> FfiMempoolMeta
    
    func slotStats()  -> FfiMempoolSlotStats
    
}

open class FfiMempool:
    FfiMempoolProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_rustylib_fn_clone_ffimempool(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_rustylib_fn_free_ffimempool(pointer, $0) }
    }

    
public static func openOrCreate(path: String)throws  -> FfiMempool {
    return try  FfiConverterTypeFfiMempool.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_constructor_ffimempool_open_or_create(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
open func flush()throws  {try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_method_ffimempool_flush(self.uniffiClonePointer(),$0
    )
}
}
    
open func generation() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffimempool_generation(self.uniffiClonePointer(),$0
    )
})
}
    
open func liveCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffimempool_live_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func meta() -> FfiMempoolMeta {
    return try!  FfiConverterTypeFfiMempoolMeta.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffimempool_meta(self.uniffiClonePointer(),$0
    )
})
}
    
open func slotStats() -> FfiMempoolSlotStats {
    return try!  FfiConverterTypeFfiMempoolSlotStats.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffimempool_slot_stats(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMempool: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiMempool

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiMempool {
        return FfiMempool(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiMempool) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMempool {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiMempool, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMempool_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiMempool {
    return try FfiConverterTypeFfiMempool.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMempool_lower(_ value: FfiMempool) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiMempool.lower(value)
}




public protocol FfiQueryProtocol : AnyObject {
    
    func blockQueueCount()  -> UInt64
    
    func blockQueueMaxHeight()  -> UInt64?
    
    func getTxByTxid(txidHex: String) throws  -> FfiTxRecord?
    
    func isOutpointSpent(txidHex: String, vout: UInt32) throws  -> Bool
    
    func tipHeight()  -> UInt64?
    
}

open class FfiQuery:
    FfiQueryProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_rustylib_fn_clone_ffiquery(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_rustylib_fn_free_ffiquery(pointer, $0) }
    }

    
public static func openOrCreate(path: String)throws  -> FfiQuery {
    return try  FfiConverterTypeFfiQuery.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_constructor_ffiquery_open_or_create(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
open func blockQueueCount() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffiquery_block_queue_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func blockQueueMaxHeight() -> UInt64? {
    return try!  FfiConverterOptionUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffiquery_block_queue_max_height(self.uniffiClonePointer(),$0
    )
})
}
    
open func getTxByTxid(txidHex: String)throws  -> FfiTxRecord? {
    return try  FfiConverterOptionTypeFfiTxRecord.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_method_ffiquery_get_tx_by_txid(self.uniffiClonePointer(),
        FfiConverterString.lower(txidHex),$0
    )
})
}
    
open func isOutpointSpent(txidHex: String, vout: UInt32)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_method_ffiquery_is_outpoint_spent(self.uniffiClonePointer(),
        FfiConverterString.lower(txidHex),
        FfiConverterUInt32.lower(vout),$0
    )
})
}
    
open func tipHeight() -> UInt64? {
    return try!  FfiConverterOptionUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffiquery_tip_height(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiQuery: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiQuery

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiQuery {
        return FfiQuery(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiQuery) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiQuery {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiQuery, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiQuery_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiQuery {
    return try FfiConverterTypeFfiQuery.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiQuery_lower(_ value: FfiQuery) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiQuery.lower(value)
}




public protocol FfiStoreProtocol : AnyObject {
    
    func getHeaderByHash(hashHex: String) throws  -> FfiHeaderRecord?
    
    func getTxByTxid(txidHex: String) throws  -> FfiTxRecord?
    
    func headerCount()  -> UInt64
    
    func tipHeight()  -> UInt64?
    
}

open class FfiStore:
    FfiStoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_rustylib_fn_clone_ffistore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_rustylib_fn_free_ffistore(pointer, $0) }
    }

    
public static func create(path: String)throws  -> FfiStore {
    return try  FfiConverterTypeFfiStore.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_constructor_ffistore_create(
        FfiConverterString.lower(path),$0
    )
})
}
    
public static func `open`(path: String)throws  -> FfiStore {
    return try  FfiConverterTypeFfiStore.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_constructor_ffistore_open(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
open func getHeaderByHash(hashHex: String)throws  -> FfiHeaderRecord? {
    return try  FfiConverterOptionTypeFfiHeaderRecord.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_method_ffistore_get_header_by_hash(self.uniffiClonePointer(),
        FfiConverterString.lower(hashHex),$0
    )
})
}
    
open func getTxByTxid(txidHex: String)throws  -> FfiTxRecord? {
    return try  FfiConverterOptionTypeFfiTxRecord.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_method_ffistore_get_tx_by_txid(self.uniffiClonePointer(),
        FfiConverterString.lower(txidHex),$0
    )
})
}
    
open func headerCount() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffistore_header_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func tipHeight() -> UInt64? {
    return try!  FfiConverterOptionUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_method_ffistore_tip_height(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiStore {
        return FfiStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiStore {
    return try FfiConverterTypeFfiStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStore_lower(_ value: FfiStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiStore.lower(value)
}


public struct FfiHeaderRecord {
    public var prevFk: UInt64
    public var version: Int32
    public var timestamp: UInt32
    public var bits: UInt32
    public var nonce: UInt32
    public var merkleRoot: String
    public var hash: String
    public var size: UInt32
    public var weight: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(prevFk: UInt64, version: Int32, timestamp: UInt32, bits: UInt32, nonce: UInt32, merkleRoot: String, hash: String, size: UInt32, weight: UInt32) {
        self.prevFk = prevFk
        self.version = version
        self.timestamp = timestamp
        self.bits = bits
        self.nonce = nonce
        self.merkleRoot = merkleRoot
        self.hash = hash
        self.size = size
        self.weight = weight
    }
}



extension FfiHeaderRecord: Equatable, Hashable {
    public static func ==(lhs: FfiHeaderRecord, rhs: FfiHeaderRecord) -> Bool {
        if lhs.prevFk != rhs.prevFk {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.bits != rhs.bits {
            return false
        }
        if lhs.nonce != rhs.nonce {
            return false
        }
        if lhs.merkleRoot != rhs.merkleRoot {
            return false
        }
        if lhs.hash != rhs.hash {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.weight != rhs.weight {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(prevFk)
        hasher.combine(version)
        hasher.combine(timestamp)
        hasher.combine(bits)
        hasher.combine(nonce)
        hasher.combine(merkleRoot)
        hasher.combine(hash)
        hasher.combine(size)
        hasher.combine(weight)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHeaderRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHeaderRecord {
        return
            try FfiHeaderRecord(
                prevFk: FfiConverterUInt64.read(from: &buf), 
                version: FfiConverterInt32.read(from: &buf), 
                timestamp: FfiConverterUInt32.read(from: &buf), 
                bits: FfiConverterUInt32.read(from: &buf), 
                nonce: FfiConverterUInt32.read(from: &buf), 
                merkleRoot: FfiConverterString.read(from: &buf), 
                hash: FfiConverterString.read(from: &buf), 
                size: FfiConverterUInt32.read(from: &buf), 
                weight: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiHeaderRecord, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.prevFk, into: &buf)
        FfiConverterInt32.write(value.version, into: &buf)
        FfiConverterUInt32.write(value.timestamp, into: &buf)
        FfiConverterUInt32.write(value.bits, into: &buf)
        FfiConverterUInt32.write(value.nonce, into: &buf)
        FfiConverterString.write(value.merkleRoot, into: &buf)
        FfiConverterString.write(value.hash, into: &buf)
        FfiConverterUInt32.write(value.size, into: &buf)
        FfiConverterUInt32.write(value.weight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHeaderRecord_lift(_ buf: RustBuffer) throws -> FfiHeaderRecord {
    return try FfiConverterTypeFfiHeaderRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHeaderRecord_lower(_ value: FfiHeaderRecord) -> RustBuffer {
    return FfiConverterTypeFfiHeaderRecord.lower(value)
}


public struct FfiMempoolMeta {
    public var generation: UInt64
    public var slotCap: UInt32
    public var liveCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(generation: UInt64, slotCap: UInt32, liveCount: UInt32) {
        self.generation = generation
        self.slotCap = slotCap
        self.liveCount = liveCount
    }
}



extension FfiMempoolMeta: Equatable, Hashable {
    public static func ==(lhs: FfiMempoolMeta, rhs: FfiMempoolMeta) -> Bool {
        if lhs.generation != rhs.generation {
            return false
        }
        if lhs.slotCap != rhs.slotCap {
            return false
        }
        if lhs.liveCount != rhs.liveCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(generation)
        hasher.combine(slotCap)
        hasher.combine(liveCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMempoolMeta: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMempoolMeta {
        return
            try FfiMempoolMeta(
                generation: FfiConverterUInt64.read(from: &buf), 
                slotCap: FfiConverterUInt32.read(from: &buf), 
                liveCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMempoolMeta, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.generation, into: &buf)
        FfiConverterUInt32.write(value.slotCap, into: &buf)
        FfiConverterUInt32.write(value.liveCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMempoolMeta_lift(_ buf: RustBuffer) throws -> FfiMempoolMeta {
    return try FfiConverterTypeFfiMempoolMeta.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMempoolMeta_lower(_ value: FfiMempoolMeta) -> RustBuffer {
    return FfiConverterTypeFfiMempoolMeta.lower(value)
}


public struct FfiMempoolSlotStats {
    public var free: UInt32
    public var live: UInt32
    public var dead: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(free: UInt32, live: UInt32, dead: UInt32) {
        self.free = free
        self.live = live
        self.dead = dead
    }
}



extension FfiMempoolSlotStats: Equatable, Hashable {
    public static func ==(lhs: FfiMempoolSlotStats, rhs: FfiMempoolSlotStats) -> Bool {
        if lhs.free != rhs.free {
            return false
        }
        if lhs.live != rhs.live {
            return false
        }
        if lhs.dead != rhs.dead {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(free)
        hasher.combine(live)
        hasher.combine(dead)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMempoolSlotStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMempoolSlotStats {
        return
            try FfiMempoolSlotStats(
                free: FfiConverterUInt32.read(from: &buf), 
                live: FfiConverterUInt32.read(from: &buf), 
                dead: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMempoolSlotStats, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.free, into: &buf)
        FfiConverterUInt32.write(value.live, into: &buf)
        FfiConverterUInt32.write(value.dead, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMempoolSlotStats_lift(_ buf: RustBuffer) throws -> FfiMempoolSlotStats {
    return try FfiConverterTypeFfiMempoolSlotStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMempoolSlotStats_lower(_ value: FfiMempoolSlotStats) -> RustBuffer {
    return FfiConverterTypeFfiMempoolSlotStats.lower(value)
}


public struct FfiTxInfo {
    public var txid: String
    public var wtxid: String
    public var version: Int32
    public var locktime: UInt32
    public var inputCount: UInt32
    public var outputCount: UInt32
    public var weight: UInt64
    public var vsize: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txid: String, wtxid: String, version: Int32, locktime: UInt32, inputCount: UInt32, outputCount: UInt32, weight: UInt64, vsize: UInt64) {
        self.txid = txid
        self.wtxid = wtxid
        self.version = version
        self.locktime = locktime
        self.inputCount = inputCount
        self.outputCount = outputCount
        self.weight = weight
        self.vsize = vsize
    }
}



extension FfiTxInfo: Equatable, Hashable {
    public static func ==(lhs: FfiTxInfo, rhs: FfiTxInfo) -> Bool {
        if lhs.txid != rhs.txid {
            return false
        }
        if lhs.wtxid != rhs.wtxid {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        if lhs.locktime != rhs.locktime {
            return false
        }
        if lhs.inputCount != rhs.inputCount {
            return false
        }
        if lhs.outputCount != rhs.outputCount {
            return false
        }
        if lhs.weight != rhs.weight {
            return false
        }
        if lhs.vsize != rhs.vsize {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txid)
        hasher.combine(wtxid)
        hasher.combine(version)
        hasher.combine(locktime)
        hasher.combine(inputCount)
        hasher.combine(outputCount)
        hasher.combine(weight)
        hasher.combine(vsize)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTxInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTxInfo {
        return
            try FfiTxInfo(
                txid: FfiConverterString.read(from: &buf), 
                wtxid: FfiConverterString.read(from: &buf), 
                version: FfiConverterInt32.read(from: &buf), 
                locktime: FfiConverterUInt32.read(from: &buf), 
                inputCount: FfiConverterUInt32.read(from: &buf), 
                outputCount: FfiConverterUInt32.read(from: &buf), 
                weight: FfiConverterUInt64.read(from: &buf), 
                vsize: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTxInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterString.write(value.wtxid, into: &buf)
        FfiConverterInt32.write(value.version, into: &buf)
        FfiConverterUInt32.write(value.locktime, into: &buf)
        FfiConverterUInt32.write(value.inputCount, into: &buf)
        FfiConverterUInt32.write(value.outputCount, into: &buf)
        FfiConverterUInt64.write(value.weight, into: &buf)
        FfiConverterUInt64.write(value.vsize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTxInfo_lift(_ buf: RustBuffer) throws -> FfiTxInfo {
    return try FfiConverterTypeFfiTxInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTxInfo_lower(_ value: FfiTxInfo) -> RustBuffer {
    return FfiConverterTypeFfiTxInfo.lower(value)
}


public struct FfiTxRecord {
    public var txid: String
    public var version: Int32
    public var locktime: UInt32
    public var inputCount: UInt32
    public var outputCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txid: String, version: Int32, locktime: UInt32, inputCount: UInt32, outputCount: UInt32) {
        self.txid = txid
        self.version = version
        self.locktime = locktime
        self.inputCount = inputCount
        self.outputCount = outputCount
    }
}



extension FfiTxRecord: Equatable, Hashable {
    public static func ==(lhs: FfiTxRecord, rhs: FfiTxRecord) -> Bool {
        if lhs.txid != rhs.txid {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        if lhs.locktime != rhs.locktime {
            return false
        }
        if lhs.inputCount != rhs.inputCount {
            return false
        }
        if lhs.outputCount != rhs.outputCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(txid)
        hasher.combine(version)
        hasher.combine(locktime)
        hasher.combine(inputCount)
        hasher.combine(outputCount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTxRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTxRecord {
        return
            try FfiTxRecord(
                txid: FfiConverterString.read(from: &buf), 
                version: FfiConverterInt32.read(from: &buf), 
                locktime: FfiConverterUInt32.read(from: &buf), 
                inputCount: FfiConverterUInt32.read(from: &buf), 
                outputCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTxRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterInt32.write(value.version, into: &buf)
        FfiConverterUInt32.write(value.locktime, into: &buf)
        FfiConverterUInt32.write(value.inputCount, into: &buf)
        FfiConverterUInt32.write(value.outputCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTxRecord_lift(_ buf: RustBuffer) throws -> FfiTxRecord {
    return try FfiConverterTypeFfiTxRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTxRecord_lower(_ value: FfiTxRecord) -> RustBuffer {
    return FfiConverterTypeFfiTxRecord.lower(value)
}


public enum RustyError {

    
    
    case InvalidInput
    case ConsensusError
    case StoreError
    case MempoolError
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustyError: FfiConverterRustBuffer {
    typealias SwiftType = RustyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput
        case 2: return .ConsensusError
        case 3: return .StoreError
        case 4: return .MempoolError

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RustyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidInput:
            writeInt(&buf, Int32(1))
        
        
        case .ConsensusError:
            writeInt(&buf, Int32(2))
        
        
        case .StoreError:
            writeInt(&buf, Int32(3))
        
        
        case .MempoolError:
            writeInt(&buf, Int32(4))
        
        }
    }
}


extension RustyError: Equatable, Hashable {}

extension RustyError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiHeaderRecord: FfiConverterRustBuffer {
    typealias SwiftType = FfiHeaderRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiHeaderRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiHeaderRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiTxRecord: FfiConverterRustBuffer {
    typealias SwiftType = FfiTxRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiTxRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiTxRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
public func addressNetwork(address: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_address_network(
        FfiConverterString.lower(address),$0
    )
})
}
public func blockHashFromHeader(headerHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_block_hash_from_header(
        FfiConverterString.lower(headerHex),$0
    )
})
}
public func blockSubsidy(height: UInt32, network: String)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_block_subsidy(
        FfiConverterUInt32.lower(height),
        FfiConverterString.lower(network),$0
    )
})
}
public func checkBlockWire(blockHex: String)throws  {try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_check_block_wire(
        FfiConverterString.lower(blockHex),$0
    )
}
}
public func feeBucketCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_bucket_count($0
    )
})
}
public func feeBucketEdges() -> [UInt64] {
    return try!  FfiConverterSequenceUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_bucket_edges($0
    )
})
}
public func feeBucketIndex(rateSatPerKvb: UInt64) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_bucket_index(
        FfiConverterUInt64.lower(rateSatPerKvb),$0
    )
})
}
public func feeCapacityWu(nBlocks: UInt32) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_capacity_wu(
        FfiConverterUInt32.lower(nBlocks),$0
    )
})
}
public func feeDefaultCandidateRates() -> [UInt64] {
    return try!  FfiConverterSequenceUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_default_candidate_rates($0
    )
})
}
public func feeEffectiveCapacityWu(nBlocks: UInt32) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_effective_capacity_wu(
        FfiConverterUInt32.lower(nBlocks),$0
    )
})
}
public func feeHorizonSecs(nBlocks: UInt32) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_horizon_secs(
        FfiConverterUInt32.lower(nBlocks),$0
    )
})
}
public func feeMinRateForCapacitySimple(stockAbove: UInt64, inflowWuPerSByBucket: [UInt64], nBlocks: UInt32, candidateRates: [UInt64]) -> UInt64? {
    return try!  FfiConverterOptionUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_min_rate_for_capacity_simple(
        FfiConverterUInt64.lower(stockAbove),
        FfiConverterSequenceUInt64.lower(inflowWuPerSByBucket),
        FfiConverterUInt32.lower(nBlocks),
        FfiConverterSequenceUInt64.lower(candidateRates),$0
    )
})
}
public func feeProjectedInflowWuAbove(inflowWuPerSByBucket: [UInt64], rateSatPerKvb: UInt64, horizonSecs: UInt64) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_projected_inflow_wu_above(
        FfiConverterSequenceUInt64.lower(inflowWuPerSByBucket),
        FfiConverterUInt64.lower(rateSatPerKvb),
        FfiConverterUInt64.lower(horizonSecs),$0
    )
})
}
public func feeRateSatPerKvb(feeSat: UInt64, weight: UInt64) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_fee_rate_sat_per_kvb(
        FfiConverterUInt64.lower(feeSat),
        FfiConverterUInt64.lower(weight),$0
    )
})
}
public func hash256(bytes: Data) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_hash256(
        FfiConverterData.lower(bytes),$0
    )
})
}
public func hexDecode(hex: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_hex_decode(
        FfiConverterString.lower(hex),$0
    )
})
}
public func hexEncode(bytes: Data) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_hex_encode(
        FfiConverterData.lower(bytes),$0
    )
})
}
public func isAnnexStandard(annexHex: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_is_annex_standard(
        FfiConverterString.lower(annexHex),$0
    )
})
}
public func medianTimePastTimes(times: [UInt32]) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_median_time_past_times(
        FfiConverterSequenceUInt32.lower(times),$0
    )
})
}
public func meetsMinRelayFee(feeSat: UInt64, weight: UInt64) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rustylib_fn_func_meets_min_relay_fee(
        FfiConverterUInt64.lower(feeSat),
        FfiConverterUInt64.lower(weight),$0
    )
})
}
public func parseTx(txHex: String)throws  -> FfiTxInfo {
    return try  FfiConverterTypeFfiTxInfo.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_parse_tx(
        FfiConverterString.lower(txHex),$0
    )
})
}
public func rbitcoinSubversion(comments: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_rbitcoin_subversion(
        FfiConverterSequenceString.lower(comments),$0
    )
})
}
public func rbitcoinVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rbitcoin_version($0
    )
})
}
public func rustAdd(a: UInt32, b: UInt32) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rust_add(
        FfiConverterUInt32.lower(a),
        FfiConverterUInt32.lower(b),$0
    )
})
}
public func rustHello() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rust_hello($0
    )
})
}
public func scriptSigops(scriptHex: String, accurate: Bool)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_script_sigops(
        FfiConverterString.lower(scriptHex),
        FfiConverterBool.lower(accurate),$0
    )
})
}
public func txidFromHex(txHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_txid_from_hex(
        FfiConverterString.lower(txHex),$0
    )
})
}
public func validateAddress(address: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rustylib_fn_func_validate_address(
        FfiConverterString.lower(address),$0
    )
})
}
public func validateHeaderOnParent(headerHex: String, network: String, height: UInt32, parentMtp: UInt32, expectedBits: UInt32)throws  {try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_validate_header_on_parent(
        FfiConverterString.lower(headerHex),
        FfiConverterString.lower(network),
        FfiConverterUInt32.lower(height),
        FfiConverterUInt32.lower(parentMtp),
        FfiConverterUInt32.lower(expectedBits),$0
    )
}
}
public func verifyTxScripts(prevoutsHex: [String], txHex: String)throws  {try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_verify_tx_scripts(
        FfiConverterSequenceString.lower(prevoutsHex),
        FfiConverterString.lower(txHex),$0
    )
}
}
public func virtualSize(weight: UInt64) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_rustylib_fn_func_virtual_size(
        FfiConverterUInt64.lower(weight),$0
    )
})
}
public func wtxidFromHex(txHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeRustyError.lift) {
    uniffi_rustylib_fn_func_wtxid_from_hex(
        FfiConverterString.lower(txHex),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rustylib_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rustylib_checksum_func_address_network() != 7866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_block_hash_from_header() != 48933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_block_subsidy() != 16642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_check_block_wire() != 22734) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_bucket_count() != 44190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_bucket_edges() != 59685) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_bucket_index() != 58372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_capacity_wu() != 63938) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_default_candidate_rates() != 50688) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_effective_capacity_wu() != 53442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_horizon_secs() != 18777) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_min_rate_for_capacity_simple() != 4521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_projected_inflow_wu_above() != 562) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_fee_rate_sat_per_kvb() != 56144) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_hash256() != 5458) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_hex_decode() != 45211) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_hex_encode() != 31720) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_is_annex_standard() != 15473) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_median_time_past_times() != 24970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_meets_min_relay_fee() != 27158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_parse_tx() != 26241) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rbitcoin_subversion() != 54893) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rbitcoin_version() != 47205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rust_add() != 47653) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rust_hello() != 11814) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_script_sigops() != 10909) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_txid_from_hex() != 27347) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_validate_address() != 11887) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_validate_header_on_parent() != 9664) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_verify_tx_scripts() != 58820) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_virtual_size() != 6608) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_wtxid_from_hex() != 62498) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffimempool_flush() != 54725) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffimempool_generation() != 36589) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffimempool_live_count() != 13707) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffimempool_meta() != 51552) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffimempool_slot_stats() != 60716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffiquery_block_queue_count() != 45316) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffiquery_block_queue_max_height() != 61436) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffiquery_get_tx_by_txid() != 24667) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffiquery_is_outpoint_spent() != 59128) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffiquery_tip_height() != 22733) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffistore_get_header_by_hash() != 58892) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffistore_get_tx_by_txid() != 7572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffistore_header_count() != 37489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_ffistore_tip_height() != 61582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_constructor_ffimempool_open_or_create() != 36938) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_constructor_ffiquery_open_or_create() != 65007) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_constructor_ffistore_create() != 42995) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_constructor_ffistore_open() != 41108) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:disable all