[package]
name = "rustylib"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]
name = "rustylib"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.28.0", features = [ "cli" ] }
rbitcoin-primitives = { workspace = true }
rbitcoin-consensus = { workspace = true }
rbitcoin-store = { workspace = true }
rbitcoin-query = { workspace = true }
bitcoin = { workspace = true }

[dev-dependencies]
tempfile = "3"

[build-dependencies]
uniffi = { version = "0.28.0", features = [ "build" ] }
