[package]
name = "rbitcoin-net"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Bitcoin P2P networking (headers + block download/serve)"

[dependencies]
rbitcoin-primitives = { workspace = true }
rbitcoin-log = { workspace = true }
rbitcoin-consensus = { workspace = true }
rbitcoin-query = { workspace = true }
rbitcoin-store = { workspace = true }
rbitcoin-mempool = { workspace = true }
bitcoin = { workspace = true }
bip324 = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
